name: Notify Discord (Push)

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
      - docs/**

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Discordへ通知を送信
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_PUSH }}
        run: bash scripts/send_push.sh
